package tests.trees;

import static org.junit.Assert.*;
import org.junit.Test;

import tree.BasicNode;
import tree.BinarySearchTree;

import java.util.Arrays;
import java.util.List;

/**
 * TODO: Insert description here. (generated by anupams)
 */
public class BinarySearchTreeTest {

  @Test
  public void treeHeightBalanced_returnsTrue() {
    Integer arr[] = {50,25,75,10,30,60,90,4,12,27,40,55,65,80,99};
    assertTrue(BinarySearchTree.isHeigthBalanced(generateTree(arr)));
  }

  @Test
  public void treeHeightBalanced_returnsFalse() {
    Integer arr[] = {1,2,3,4,5,6,7,8,9};
    assertFalse(BinarySearchTree.isHeigthBalanced(generateTree(arr)));
  }

  private <T extends Comparable<T>> BasicNode<T>  generateTree(T arr[]) {
    BasicNode<T> root = BinarySearchTree.generateBs(Arrays.asList(arr));
    return root;
  }
}
